/*
Main program of calculator example.
Simply invoke the parser generated by bison, and then display the output.
*/

#include <stdio.h>
#include <stdlib.h>
#include <getopt.h>
#include "decl.h"
#include "expr.h"
#include "stmt.h"
#include "symbol.h"
#include "type.h"
#include "param_list.h"

/* Clunky: Declare the parse function generated from parser.bison */
extern int yyparse();

extern FILE* yyin;

/* Clunky: Declare the result of the parser from parser.bison */
extern struct decl * parser_result;

int main( int argc, char *argv[] )
{
    int opt;
    static struct option long_options[] = {
	{"parse", 1, 0, 'p'}
    };
    int long_index = 0;
    opt = getopt_long_only (argc, argv, "",
		long_options, &long_index);
    switch (opt) {
		case 'p':
			yyin = fopen( optarg, "r" );
      if (!yyin) {
        printf("file not opened!\n");
        exit(1);
      }
 			do {
 				if (yyparse() == 0 && yyin == 0) {
 					decl_print(parser_result, 0);
 					exit(0);
 				} else {
 					exit(1);
 				}
 			} while (1);
 				/*
       			if (yyparse() == 0) {
       				decl_print(parser_result, 0);
       				return 0;
       			} else {
       				exit(1);
       			}
       			*/
  			break;
		default: 
			exit(1);
     }
}

